{% set version = "4.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-olinkanalyze
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/OlinkAnalyze_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/OlinkAnalyze/OlinkAnalyze_{{ version }}.tar.gz
  sha256: f15f3bd3d0ebd3263729c11660d8f78e3d6d5a8e0b666581ecc0280405a77957

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.0.0
    - r-broom
    - r-car
    - r-dplyr
    - r-emmeans
    - r-forcats
    - r-generics
    - r-ggplot2
    - r-ggpubr
    - r-ggrepel
    - r-lme4
    - r-lmertest
    - r-magrittr
    - r-readxl
    - r-rlang
    - r-rstatix
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-zip
  run:
    - r-base >=4.0.0
    - r-broom
    - r-car
    - r-dplyr
    - r-emmeans
    - r-forcats
    - r-generics
    - r-ggplot2
    - r-ggpubr
    - r-ggrepel
    - r-lme4
    - r-lmertest
    - r-magrittr
    - r-readxl
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-zip

test:
  commands:
    - $R -e "library('OlinkAnalyze')"           # [not win]
    - "\"%R%\" -e \"library('OlinkAnalyze')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=OlinkAnalyze
  license: AGPL-3.0-or-later
  summary: A collection of functions to facilitate analysis of proteomic data from Olink, primarily NPX data that has been exported from Olink Software. The functions also work on QUANT data from Olink by log- transforming the QUANT data. The functions are focused on reading data, facilitating data wrangling and quality
    control analysis, performing statistical analysis and generating figures to visualize the results of the statistical analysis. The goal of this package is to help users extract biological insights from proteomic data run on the Olink platform.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3

extra:
  recipe-maintainers:
    - AskPascal
